# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161231190244 on 2017-05-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(max_length=8000)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('news_paper', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('fetched_url', models.URLField(max_length=400)),
            ],
            options={
                'db_table': 'editorials',
            },
        ),
    ]
