# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(max_length=8000)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('news_paper', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('fetched_url', models.URLField(max_length=400)),
            ],
            options={
                'db_table': 'editorials',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
