# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorials',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
