# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0002_editorials_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorials',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
